server {
    listen 80;
    server_name localhost udriving.com.br www.udriving.com.br;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    root /usr/share/nginx/html;
    index index.html;
}
